spring:
  application:
    name: eureka-server
  server:
    port: 8112
  eureka:
    instance:
      hostname: register2
    client:
      register-with-eureka: true
      serviceUrl.defaultZone: http://register1:8111/eureka/